### ISSUE TITLE
USB3 Port is not working ?

### ISSUE THREAD

**Issue by Pix13** [jayanta525/rk3328-rock-pi-e#2]
I tried to plug a block device and a wifi device: lsusb stayed empty, and dmesg did not log any thing, maybe something missing in the device tree ?

**Comment by jayanta525** [comment]
Yes, the DTS node was set to work in OTG mode. I have fixed it and rebased it to the current master. 

I am currently adjusting the image to use kmod-packages from a separate repository, such that users don't have to compile every time they want to include a new kmod-package. It can simply be done with `opkg install kmod--`

I will update you when the builds are ready.

This is the dmesg when USB is plugged:

```
[ 4455.597092] usb 4-1: new high-speed USB device number 2 using xhci-hcd
[ 4455.747427] usb-storage 4-1:1.0: USB Mass Storage device detected
[ 4455.748962] scsi host0: usb-storage 4-1:1.0
[ 4456.766378] scsi 0:0:0:0: Direct-Access     SanDisk  Cruzer Blade     1.27 PQ: 0 ANSI: 6
[ 4456.771988] sd 0:0:0:0: [sda] 15633408 512-byte logical blocks: (8.00 GB/7.45 GiB)
[ 4456.773648] sd 0:0:0:0: [sda] Write Protect is off
[ 4456.774100] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[ 4456.774895] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 4456.836017]  sda: sda1 sda2
[ 4456.839784] sd 0:0:0:0: [sda] Attached SCSI removable disk
```

**Comment by jayanta525** [comment]
@Pix13 https://jayanta525.gitlab.io/openwrt-rockpie/

try `opkg update && opkg install kmod-usb-storage`
